# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imgresampling.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import os
import random
from PIL import Image, ImageOps, ImageFile, ImageDraw, ImageFont
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(371, 29)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.resampler)
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "이미지 리샘플링"))
    def resampler(self):
        img_lst = QFileDialog.getExistingDirectory()
        print(img_lst)
        for file in os.scandir(img_lst):
            print(file.path)
            if not '.jpg' in file.path and not '.png' in file.path and not '.jepg' in file.path:
                continue

            img = Image.open(file.path)

            randomi = random.randrange(60, 100)
            if '.jpg' in file.path:
                img.save(file.path, 'JPEG', quality=randomi)
            if '.png' in file.path:
                img.save(file.path, 'png', quality=randomi)
            if '.jepg' in file.path:
                img.save(file.path, 'JPEG', quality=randomi)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
